### ISSUE TITLE
Product Discussion

### ISSUE THREAD

**Issue by wilbertliu** [wilbertliu/redux-ecosystem#1]
![68747470733a2f2f692e696d6775722e636f6d2f456836775370582e706e67](https://user-images.githubusercontent.com/357537/35623987-1e79feea-06c0-11e8-8e5a-e49e797be9c4.png)

Hello! 👋🏻

As everybody knows, the attached mockup was made by @markerikson. Based on that, I think it's quite obvious on things that we need to build. But this issue is not for that. It's to discuss the missing, the invisible, the hidden, the details that might popped up as we uncover it.

We want to make one-stop website that people will think and visit if they want to search for Redux-related libraries.

In order to do that, here are the details I feel I need to write :

- We need to show a loading view when we are performing API call.
- When category is changed, the page shows loading view and update the result.
  - Similar thing applies to subcategory and all of the filters.
- The category, subcategory, and filters should be sticky when user performs scroll across the table.
- The table's headers (Name, URL, Description, GitHub stars, and NPM downloads / mo) could be clicked.
  - When user does so, the page shows loading view, change the arrow icon, and update the result.
  - When user changes category, subcategory, or filters, all of the arrow icons should be back to normal and no sort performed. Of course the page should show loading view, change the arrow icons, and update the result.
- The link on URL column should be opened on new tab.

And here are few questions that I feel would improve the product :
- Would it be good if we show "All Category" for category and "All Subcategory" for subcategory sorted by GitHub stars, then NPM downloads, and so on at first? That should be good I think? Except when people come by hitting their bookmark that possibly has some query strings that we need to tackle.
- Would it be good if the filters are unchecked at first? Since it will make user think about something that he / she doesn't do nor willing to see so.
- Would it be good if we replace everything that could be replaced by emoji (e.g GitHub stars)? Personally I feel that will become more casual and more fun for people. 😀
- Would it be good if the selected date is the beginning of current month? It's a good threshold to filter the active or non active repo I think. Not so long, but not so short to the current date as well.
- Is 50 will be a good threshold for GitHub stars? Would it be better if it's 0 at first?
- Is 100 will be a good threshold for NPM downloads? Would it be better if it's 0 at first?
- Would it be good if we remove the URL column, and just make each name of the repo linkable to its respective GitHub page?

Do you feel there's something missing from this? Is there something you feel disagree with? Feel free to speak up your thoughts, since it will benefit our end-product. Your thoughts matter. 🙏🏻

**Comment by dberget** [comment]
👋 - Everything looks pretty good to me, i've added some thoughts to your questions and some additional things below. 

> Would it be good if we show "All Category" for category and "All Subcategory" for subcategory sorted by GitHub stars, then NPM downloads, and so on at first? 

> Would it be good if the filters are unchecked at first? Since it will make user think about something that he / she doesn't do nor willing to see so.

>Is 50 will be a good threshold for GitHub stars? Would it be better if it's 0 at first?
Is 100 will be a good threshold for NPM downloads? Would it be better if it's 0 at first?

All of these are somewhat related so i'll respond to all at once. Since Mark is curating the list himself and applying a certain level of quality control, I think its best to not filter out anything by default. So we should default to showing all the categories/subcategories and leaving everything unchecked. 

The only thing that comes to mind on maybe filtering out by default is if we found it necessary to apply an age threshold to when a repo was last updated, but then those might just be good candidate to be deleted from the list altogether if they aren't relevant, which is Mark's problem. :)

> Would it be good if the selected date is the beginning of current month? It's a good threshold to filter the active or non active repo I think. Not so long, but not so short to the current date as well.

I'm assuming your thinking on having it unchecked by default and then having a placeholder value there? I'd vote for defaulting to "within the last 30 days", rather than the start of the current month, since it might cause some weirdness when a month is just starting.

I've also added a follow up idea on this in my additional notes section. 

> Would it be good if we remove the URL column, and just make each name of the repo linkable to its respective GitHub page?

Yeah, agreed! 

> Would it be good if we replace everything that could be replaced by emoji (e.g GitHub stars)? Personally I feel that will become more casual and more fun for people. 😀

💯 🥇 👍 - Not that I think either of us would overdo it, but as long as the meaning of the emoji is clear in context then I think we should add them as we see appropriate. 

Additional Thoughts/Ideas:

- On the main/home page we could have a recently updated/added feed on the side to call out and highlight updated libs or ones recently added to the list. 
- Are you planning on forking the https://github.com/satiewaltz/reactionary repo that Mark mentioned in the issue or using another method to parse the list?

**Comment by markerikson** [comment]
Yeah, I'm not fixated on the exact display layout.  If a list of card-like entries is better than a grid, or if you've got ideas for how to better display the entries, go right ahead!

**Comment by wilbertliu** [comment]
Hello all 👋🏻,
Thanks for participating on this conversation! 🙂
Let me respond it one by one.

> If a list of card-like entries is better than a grid, or if you've got ideas for how to better display the entries, go right ahead!

I also thought about card-like UI, but I think we better do some experimentation on the UI to consider different approach that might be suitable for displaying the result. _I know you can't wait to code it @dberget_ 😄.

So @dberget, I think it's a good chance for you to code some UI alternatives, so we could tweak here and there and see which one is best. What do you think? Few PRs will be great. You just need to reference the PRs there #2. And it's okay to use dummy data at first, since what we care right now is to see how the UI works.

> The only thing that comes to mind on maybe filtering out by default is if we found it necessary to apply an age threshold to when a repo was last updated, but then those might just be good candidate to be deleted from the list altogether if they aren't relevant, which is Mark's problem. :)

I think @markerikson would not bother himself to delete those outdated repos, LOL 😅. Anyway, my take on the default filter is quite simple. When we don't apply any filter at the first state, I think it's quite obvious to just show the repos in chronological order as in database. Note that I don't mean database as an engine. Conversely, I thought about using simple JSON as the database.

> I'm assuming your thinking on having it unchecked by default and then having a placeholder value there? I'd vote for defaulting to "within the last 30 days", rather than the start of the current month, since it might cause some weirdness when a month is just starting.

True! 😀 Unchecked by default, and just a placeholder. And yes, I agree with you on the weirdness and defaulting to show placeholder within the last 30 days. That said, for example the user visits the site at `31-01-2018`, then the placeholder should be `01-01-2018` right?

> On the main/home page we could have a recently updated/added feed on the side to call out and highlight updated libs or ones recently added to the list.

Hmm.., I don't see the benefit of this at the moment. But that doesn't mean I disagree with it. It's just I can't see the benefit right now. It would be clearer when we see the prototype and play with it.

> Are you planning on forking the https://github.com/satiewaltz/reactionary repo that Mark mentioned in the issue or using another method to parse the list?

Honestly no. It's better for me to write our own parser that could run at some interval of time rather than mess up with another dependency. But if somebody wants to take it in a better way, then why not? 😄 In a meanwhile, I created #3 to discuss about this.

So, to wrap up everything – Let's discuss global things around the product here. And when there's something that needs to be discussed (and possibly made) specifically like the UI approach, I will make separate issue to hit the topic in much focused way.

Thanks! 🙏🏻

**Comment by wilbertliu** [comment]
Hello everyone 👋🏻,

I'm gonna open a discussion about the potential features that might be added to our end-product. But first of all, let's fix the non-obvious but cluttered things that might disturb us along the way.

Let me start with this question : 
**What's the single reason I (or in a broader sense – the people) visit this site?**

And I can't imagine any reason other than this, which I believe is the reason most people visit this site – I want to find a repo that could solve my problem that related to Redux. If you find any other reasons, please don't be silent and let's discuss it.

Being that said, I think there are few things that could be adjusted :

1. Since the category and subcategory will grow from time to time, I think it's wise for us to introduce a capability to search by keyword (yes, the search bar). Because then we respect the people that don't have much time to search through the list of category and subcategory to find what they want. The idea is to make the people choose whether they want to search by keyword on search bar, or searching through the list of category and subcategory ~~(not both)~~, or both.
2. I think we can remove all of the filters at the moment, because obviously people would only want to see the most trusted yet reliable repos at the first place right? And there's no point for people to waste their time adjusting those filters because again, they only want to solve problems by finding the best possible repo to do its job.
3. I think the repos that will be shown as the result should be sorted by GitHub stars then followed by NPM downloads by default (remember, people just want to see the best of the best 😀). Also, I encourage the sort things to be moved to the left (yes, replacing the filter things) with the checkbox appearance (see attachment below for example). So when the people uncheck both of those sort options, the repos should be sorted alphabetically. And yes, I only prefer those two sort options. Other than that is not necessary I think. 

![group](https://user-images.githubusercontent.com/357537/35717222-65f2d854-0810-11e8-99cb-3bac98312518.png)

I think that's all I can say for now.
If you have any thoughts, you're most welcome to bring it to the surface.

Thank you! 🙏🏻

**Comment by wilbertliu** [comment]
Since we already have a rough yet working prototype, will close this issue then! Further product discussion should be made by new issue.
