### ISSUE TITLE
UI Experiment & Prototype

### ISSUE THREAD

**Issue by wilbertliu** [wilbertliu/redux-ecosystem#2]
Howdy 👋🏻,

As what we've discussed on #1, there could be many different UIs approach to display the resulting repos. Here I make this issue to discuss specifically on every experiment that we'll make, and decide which one is best.

So @dberget, do you want to start with the mockup that @markerikson has made, and evolve from that? Also, the card-like UI.. 😀

But if anyone has any idea and has some chance to make it through code, don't be hesitant to send PR and reference the PR here.

Thank you! 🙏🏻

**Comment by dberget** [comment]
Sounds good @wilbertliu, I'll mockup some different things to get us started!

**Comment by dberget** [comment]
I'll submit a proper PR tonight but wanted to post a screenshot to get any initial feedback on the card layout. 

A few "designers" caveats: 

- I didn't do anything really with the left hand navbar yet so ignore that. 

- I could probably spend 8 hours bumping the top sort bar stuff around if i'm not careful so i'm just going to post it. I feel like it has too many icons and the spacing is a little weird at the moment. 

- Generally speaking it would probably be good to add some color?

- Any other thoughts? All feedback welcome, i'm not a professional at this. :)


![image](https://user-images.githubusercontent.com/3435711/35705622-a51e3af8-0768-11e8-8a54-f7c2085cdf2c.png)

**Comment by wilbertliu** [comment]
Hey @dberget 👋🏻😀,

Thank you for the early screenshot. I really encourage anyone to share often (and you've demonstrated it in a good way 👍🏻), so we could have a nice feedback-loop that will benefit ourselves in the long run (e.g not getting burnout, not feeling lonely, and any other mental health things).

So let me start by answering your thoughts and questions.

> I feel like it has too many icons and the spacing is a little weird at the moment.

In short yes. I've just discussed few things about this as well on #1.

> Generally speaking it would probably be good to add some color?

I feel the same! But first of all, I think it's good to put the purple color of Redux as our primary color. Of course [this one](https://redux.js.org) is a good reference if you want to take a look. Based on our primary color, there are many ways to create a color palette. One of them is to see the [catalog of design](https://dribbble.com/colors) based on the hex color. When we found something that sticks to us, you can download its color palette on the detail page. For example [this one](https://dribbble.com/shots/4174681-Birdie-Fashion-Store-Categories-Page-Animation), there's a color palette that can be downloaded on the right side. Hope that helps. 😀

Last but not least, let me shoot some thoughts :

1. Please see #1 because I highlighted some of our features that might be added or removed.
2. I think there shouldn't be a Submit link for now because there's no discussion about it on #1 yet. At least not at the moment. But About is okay though, just a minor addition that could be linked to our GitHub repo if we want to.
3. I think the grey colored box in the middle should expand until the rightmost side, unless you have planned something to be put on the right side.
4. I assume you hear me on number 3, I think it's better to widen the space between cards, so people could digest the information in a better way. Because then, too tight in spacing is disturbing, that's why we should design the whitespace as well.
5. The date inside the card is quite confusing I think. People don't know what's the intention of that date. Whether it's a creation date, update date, etc. I suggest to add some label or something if possible.

Alright, I think that's all.

Let me know what you think! 😀🙏🏻

**Comment by dberget** [comment]
Appreciate the feedback @wilbertliu, it also sounds very reasonable to me, I will update accordingly in #4!

**Comment by dberget** [comment]
Couple of things about the main/index page. I currently haven't done much with it from a design standpoint and I think we should discuss some things on it first.

- In my opinion the categories seem to be better suited for a straightforward list layout. Quicker to skim down the list this way to get to a category. For the sake of consistency though it might be worth to just use the same card layout, so open to everybody's thoughts.
- Beyond showing the sub-topics i'm not sure what else would else be useful to display. The subtopics could link directly to its location.
- Since we're displaying the entire list, and also the search bar, it seems unnecessary to have the left-nav dropdown's on this page, also the sort options don't do anything on this page so i'm thinking we should not have the sort-by options here.

Here is a very early mockup of the items with the subtopics, on one hand it feels like a lot of info but it also seems nice to have the direct navigation to a subtopic available like that. Maybe could do a hover state to display sub topics if we want.

Anyway, open to thoughts! 😄 

![image](https://user-images.githubusercontent.com/3435711/35939915-2959acf4-0c13-11e8-85b8-4889f96e9e4b.png)

**Comment by wilbertliu** [comment]
Hello @dberget 👋🏻,

More or less I thought similarly to what you did above, but my main consideration was the design on #4  will make people do more steps when they want to switch to another subcategory that's not inside the current selected category. Do you know what I mean? 😀 Now the problem with design above is also similar. Though people could choose subcategory directly because the category is listed, people will go back and forth from the result page to this **All Categories** page just for the sake of changing category / subcategory or seeing the result of repositories.

Being that said, what if we modify the design on #4 to move the sort to the bottom, and put the list of categories at the top by using [this pattern](https://dribbble.com/shots/3730853--Exploration-Web-Documentation-Search)? Yes, it's like folder, but you don't have to make it so. Just a clickable list that will expand the subcategories once it's clicked by people. Got some idea? 😉 So no dropdown anymore. Also for **Go To Subtopic**, I don't think there's benefits on showing that to people. So, that could be removed as well I think?

P.S : Note that the sort options should be checked at the initial state, because we do sort by both of those GitHub stars & NPM downloads. See #1 specifically my latest comment.

**Comment by dberget** [comment]
> Being that said, what if we modify the design on #4 to move the sort to the bottom, and put the list of categories at the top by using this pattern? Yes, it's like folder, but you don't have to make it so. Just a clickable list that will expand the subcategories once it's clicked by people. Got some idea? 😉 So no dropdown anymore. Also for Go To Subtopic, I don't think there's benefits on showing that to people. So, that could be removed as well I think?

I like that pattern a lot and think it makes a lot of sense with this situation, and if we're using that then it makes sense to remove the Go To Subtopic section. i'll get to work on it! :)

**Comment by wilbertliu** [comment]
Closing this issue for now because we just have the working prototype! 🎉
