### ISSUE TITLE
Robot Improvements

### ISSUE THREAD

**Issue by dberget** [wilbertliu/redux-ecosystem#8]
Hello,

After updating my branch to use the generated JSON, there were two things that would be helpful to change/add. 

1. It would be nice if the robot created a url slug field for each category and subcategory. Several of the names use "/" or have spaces which makes a lot of the urls not work or ugly. I'm thinking we should just use the name field and strip out any spaces or "/" for the generated slug.

2. The timestamp for the Github date has the time in the string. We should delete the T and everything after it upon creation.

Example:  "github_last_update": "2017-06-14T00:01:10Z"

Open to thoughts!

**Comment by wilbertliu** [comment]
Hi @dberget 👋🏻,

1. Sure thing, will work on this soon.
2. Why do you need that to be deleted? Is there any parsing / conversion problem? Let me know the use case if so.

**Comment by dberget** [comment]
Maybe its fine, I'm formatting it quick but thought it might be better to do it on creation rather than client side. Currently, I'm just doing the following: 

```js
const formatDate = date => {
  const formattedDate = date.split("T")
  return formattedDate[0]
}
```

**Comment by wilbertliu** [comment]
Alright, will work on that as well then! Is there anything else you might need?
I will make a PR and mention you when it's done, as usual. 😀
